"""remove unique email from invite

Revision ID: 08c968fda6eb
Revises: 720a8e798e18
Create Date: 2026-07-06 17:29:55.620240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c968fda6eb'
down_revision: Union[str, Sequence[str], None] = '720a8e798e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitations_target_email_key'), 'invitations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('invitations_target_email_key'), 'invitations', ['target_email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
