"""university

Revision ID: 1df3fc9f0dee
Revises: e5582e7ccfab
Create Date: 2026-04-26 15:52:57.147918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df3fc9f0dee'
down_revision: Union[str, Sequence[str], None] = 'e5582e7ccfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('university', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'university')
    # ### end Alembic commands ###
