"""removing orphaned data

Revision ID: 1ebcb2a65e3b
Revises: 579b9b7b3c60
Create Date: 2026-04-23 21:43:27.469792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebcb2a65e3b'
down_revision: Union[str, Sequence[str], None] = '579b9b7b3c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lesson_progress_student_id_fkey'), 'lesson_progress', type_='foreignkey')
    op.drop_constraint(op.f('lesson_progress_course_id_fkey'), 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_progress', 'enrollments', ['student_id', 'course_id'], ['student_id', 'course_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_progress_course_id_fkey'), 'lesson_progress', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('lesson_progress_student_id_fkey'), 'lesson_progress', 'user', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
