"""Add rating_count and user_rating

Revision ID: 219472202bcd
Revises: 815f514235e8
Create Date: 2026-08-12 18:30:48.453130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219472202bcd'
down_revision: Union[str, Sequence[str], None] = '815f514235e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('rating_count', sa.Integer(), server_default='1', nullable=True))
    op.add_column('enrollments', sa.Column('user_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'user_rating')
    op.drop_column('courses', 'rating_count')
    # ### end Alembic commands ###
