"""add course chat_id

Revision ID: 27c821bceb7b
Revises: ce80a313c8da
Create Date: 2026-05-02 09:17:43.323803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c821bceb7b'
down_revision: Union[str, Sequence[str], None] = 'ce80a313c8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('chat_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'courses', 'channels', ['chat_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'chat_id')
    # ### end Alembic commands ###
