"""fixed message time

Revision ID: 33fef42eecfc
Revises: bbf5f8e21fcd
Create Date: 2026-08-04 15:50:14.089658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fef42eecfc'
down_revision: Union[str, Sequence[str], None] = 'bbf5f8e21fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('role', sa.String(), server_default='student', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'role')
    # ### end Alembic commands ###
