"""Add auto_certificate to Course

Revision ID: 37fca402eb0f
Revises: be7580fc89aa
Create Date: 2026-08-14 20:38:04.370029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add auto_certificate to Course

Revision ID: 37fca402eb0f
Revises: be7580fc89aa
Create Date: 2026-08-14 20:38:04.370029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fca402eb0f'
down_revision: Union[str, Sequence[str], None] = 'be7580fc89aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('auto_certificate', sa.Boolean(), server_default='true', nullable=False))
    op.execute("UPDATE courses SET auto_certificate = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'auto_certificate')
    # ### end Alembic commands ###
