"""added progress saves

Revision ID: 3a21e73eaf9f
Revises: 07bde7d499dc
Create Date: 2026-04-23 18:14:02.669792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a21e73eaf9f'
down_revision: Union[str, Sequence[str], None] = '07bde7d499dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'concluded')
    op.drop_column('modules', 'concluded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('concluded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('concluded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
