"""Add last_read_at and metadata_payload

Revision ID: 45b007b188ae
Revises: 37fca402eb0f
Create Date: 2026-08-16 21:36:18.628792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b007b188ae'
down_revision: Union[str, Sequence[str], None] = '37fca402eb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_members', sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_members', 'last_read_at')
    # ### end Alembic commands ###
