"""added login otp step

Revision ID: 4d845b128621
Revises: 62f3b90af198
Create Date: 2026-05-17 15:07:50.224347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d845b128621'
down_revision: Union[str, Sequence[str], None] = '62f3b90af198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_otps', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'signup_otps', ['email'])
    op.drop_column('signup_otps', 'otp_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_otps', sa.Column('otp_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'signup_otps', type_='unique')
    op.drop_column('signup_otps', 'code')
    # ### end Alembic commands ###
