"""added completed at to enrollment

Revision ID: 579b9b7b3c60
Revises: 3a21e73eaf9f
Create Date: 2026-04-23 20:42:32.122857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579b9b7b3c60'
down_revision: Union[str, Sequence[str], None] = '3a21e73eaf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'completed_at')
    # ### end Alembic commands ###
