"""university

Revision ID: 5af7428c0843
Revises: 1df3fc9f0dee
Create Date: 2026-04-27 15:15:37.818118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af7428c0843'
down_revision: Union[str, Sequence[str], None] = '1df3fc9f0dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_materials', sa.Column('is_generating', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_materials', 'is_generating')
    # ### end Alembic commands ###
