"""atudy plans

Revision ID: 62b05a19b517
Revises: bd1e19dd82d6
Create Date: 2026-04-28 11:45:44.672326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b05a19b517'
down_revision: Union[str, Sequence[str], None] = 'bd1e19dd82d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('questions_material_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'study_materials', ['material_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_material_id_fkey'), 'questions', 'study_materials', ['material_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
