"""added login otp step

Revision ID: 62f3b90af198
Revises: d6068eaa7b16
Create Date: 2026-05-15 18:06:00.071401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f3b90af198'
down_revision: Union[str, Sequence[str], None] = 'd6068eaa7b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_otps',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_foreign_key(None, 'courses', 'channels', ['chat_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_table('signup_otps')
    # ### end Alembic commands ###
