"""added_chat_tables

Revision ID: 71ebf93cc0cc
Revises: 1ebcb2a65e3b
Create Date: 2026-04-23 22:19:31.136569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ebf93cc0cc'
down_revision: Union[str, Sequence[str], None] = '1ebcb2a65e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
