"""added passwordotp

Revision ID: 720a8e798e18
Revises: abfefdf16ac0
Create Date: 2026-05-19 15:02:10.946656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720a8e798e18'
down_revision: Union[str, Sequence[str], None] = 'abfefdf16ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'password_reset_otps', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_otps', type_='unique')
    # ### end Alembic commands ###
