"""add credits and org ai drafting entitlement tables

Revision ID: 79f59b3b693d
Revises: 917e8a2403d9
Create Date: 2026-08-07 15:40:00.372400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f59b3b693d'
down_revision: Union[str, Sequence[str], None] = '917e8a2403d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_display', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenuecat_webhook_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('app_user_id', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_revenuecat_webhook_events_app_user_id'), 'revenuecat_webhook_events', ['app_user_id'], unique=False)
    op.create_table('credit_balances',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('credit_ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_entries_id'), 'credit_ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_entries_user_id'), 'credit_ledger_entries', ['user_id'], unique=False)
    op.create_table('credit_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rc_event_id', sa.String(), nullable=False),
    sa.Column('rc_transaction_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('credits_granted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['credit_packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_purchases_id'), 'credit_purchases', ['id'], unique=False)
    op.create_index(op.f('ix_credit_purchases_rc_event_id'), 'credit_purchases', ['rc_event_id'], unique=True)
    op.create_index(op.f('ix_credit_purchases_rc_transaction_id'), 'credit_purchases', ['rc_transaction_id'], unique=False)
    op.create_index(op.f('ix_credit_purchases_user_id'), 'credit_purchases', ['user_id'], unique=False)
    op.create_table('plan_ai_drafting_configs',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('entitled', sa.Boolean(), nullable=False),
    sa.Column('monthly_draft_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('org_draft_ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='draftstatus'), nullable=False),
    sa.Column('draft_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['draft_job_id'], ['course_draft_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['Organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_draft_ledger_entries_id'), 'org_draft_ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_org_draft_ledger_entries_org_id'), 'org_draft_ledger_entries', ['org_id'], unique=False)
    op.create_table('organisation_ai_drafting_usage',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('drafts_used_this_cycle', sa.Integer(), nullable=False),
    sa.Column('cycle_start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['Organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation_ai_drafting_usage')
    op.drop_index(op.f('ix_org_draft_ledger_entries_org_id'), table_name='org_draft_ledger_entries')
    op.drop_index(op.f('ix_org_draft_ledger_entries_id'), table_name='org_draft_ledger_entries')
    op.drop_table('org_draft_ledger_entries')
    op.drop_table('plan_ai_drafting_configs')
    op.drop_index(op.f('ix_credit_purchases_user_id'), table_name='credit_purchases')
    op.drop_index(op.f('ix_credit_purchases_rc_transaction_id'), table_name='credit_purchases')
    op.drop_index(op.f('ix_credit_purchases_rc_event_id'), table_name='credit_purchases')
    op.drop_index(op.f('ix_credit_purchases_id'), table_name='credit_purchases')
    op.drop_table('credit_purchases')
    op.drop_index(op.f('ix_credit_ledger_entries_user_id'), table_name='credit_ledger_entries')
    op.drop_index(op.f('ix_credit_ledger_entries_id'), table_name='credit_ledger_entries')
    op.drop_table('credit_ledger_entries')
    op.drop_table('credit_balances')
    op.drop_index(op.f('ix_revenuecat_webhook_events_app_user_id'), table_name='revenuecat_webhook_events')
    op.drop_table('revenuecat_webhook_events')
    op.drop_table('credit_packs')
    # ### end Alembic commands ###
