"""playlist

Revision ID: 815f514235e8
Revises: 046fbad55ba7
Create Date: 2026-08-12 18:14:48.337251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815f514235e8'
down_revision: Union[str, Sequence[str], None] = '046fbad55ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('courses', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('lessons', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('modules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('playlists', sa.Column('org_id', sa.UUID(), nullable=True))
    op.add_column('playlists', sa.Column('image_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'playlists', 'Organisations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_column('playlists', 'image_url')
    op.drop_column('playlists', 'org_id')
    op.drop_column('modules', 'updated_at')
    op.drop_column('lessons', 'updated_at')
    op.drop_column('courses', 'rating')
    op.drop_column('courses', 'updated_at')
    # ### end Alembic commands ###
