"""added system messages as type

Revision ID: 8fe31e375932
Revises: 4cd6f780de9c
Create Date: 2026-04-24 13:35:47.190154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fe31e375932'
down_revision: Union[str, Sequence[str], None] = '4cd6f780de9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'type',
               existing_type=postgresql.ENUM('TEXT', 'FILE', 'POLL', 'system', name='messagetype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TEXT', 'FILE', 'POLL', 'system', name='messagetype'),
               existing_nullable=False)
    # ### end Alembic commands ###
