"""add credits and org ai drafting entitlement tables

Revision ID: 917e8a2403d9
Revises: 33fef42eecfc
Create Date: 2026-08-07 15:37:57.019871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917e8a2403d9'
down_revision: Union[str, Sequence[str], None] = '33fef42eecfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
