"""added streak

Revision ID: ce80a313c8da
Revises: 62b05a19b517
Create Date: 2026-04-28 19:36:18.936559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce80a313c8da'
down_revision: Union[str, Sequence[str], None] = '62b05a19b517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('streak', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_login_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_date')
    op.drop_column('user', 'streak')
    # ### end Alembic commands ###
