"""add_certificate_fields

Revision ID: f9809290fd03
Revises: 8fe31e375932
Create Date: 2026-04-25 01:01:06.747329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9809290fd03'
down_revision: Union[str, Sequence[str], None] = '8fe31e375932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('certificate_url', sa.String(), nullable=True))
    op.add_column('enrollments', sa.Column('credential_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'credential_id')
    op.drop_column('enrollments', 'certificate_url')
    # ### end Alembic commands ###
